import {
    SIDE_TOP as LOCATION_SIDE_TOP,
    SIDE_BOTTOM as LOCATION_SIDE_BOTTOM,
    ALIGNMENT_CENTER as LOCATION_ALIGNMENT_CENTER,
    ALIGNMENT_START as LOCATION_ALIGNMENT_START,
    ALIGNMENT_END as LOCATION_ALIGNMENT_END
} from '../locationConstants';

export const SIDE_TOP = LOCATION_SIDE_TOP;
export const SIDE_BOTTOM = LOCATION_SIDE_BOTTOM;
export const SIDES = [SIDE_TOP, SIDE_BOTTOM];

export const ALIGNMENT_CENTER = LOCATION_ALIGNMENT_CENTER;
export const ALIGNMENT_START = LOCATION_ALIGNMENT_START;
export const ALIGNMENT_END = LOCATION_ALIGNMENT_END;
export const ALIGNMENTS = [ALIGNMENT_CENTER, ALIGNMENT_START, ALIGNMENT_END];

export const TRIGGER_EVENT_CLICK = 'click';
export const TRIGGER_EVENT_HOVER = 'hover';
export const TRIGGER_EVENTS = [TRIGGER_EVENT_CLICK, TRIGGER_EVENT_HOVER];